# -*- coding: utf-8 -*-
"""Titanic_Survival_Pr01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/Chinmaybharadwaj7/21-Days-21-Projects/blob/main/Titanic_Survival_Pr01.ipynb
"""

!pip install ydata-profiling -q

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import pandas as pd
from ydata_profiling import ProfileReport

sns.set(style = 'whitegrid')

!git clone 'https://github.com/Chinmaybharadwaj7/Sample-Dataset'

df = pd.read_csv('/content/Sample-Dataset/Titanic-Dataset.csv')

df.columns

"""DATA IMPORT - Fetching the raw data from CSV"""

df.head()

df.tail()

#values that the column holds
df['Embarked'].unique()

df.info()

df.describe()

#Describes the dataset(Only numerical Column)
#Calculates the basic statistics for dataset study

df['Cabin']

df['Cabin'].value_counts()

"""DATA CLEANING - Handle Null Values or empty values

Few Statistics :

*   Mode = most frequent value
*   Median = middle value
*   Mean = average value
"""

#first we need to figure the cells which are not filled i.e. Empty
# True if Empty(Null)

df.isnull()

#total count of unknown value(null) in each column
df.isnull().sum()

#filling the empty column of 'Age' column with Median value of the same column
#Wll use Median for Numerical columns
#Median = Midlle Value of that column
median_age = df['Age'].median()
df['Age'] = df['Age'].fillna(median_age)

df.isnull().sum()

#filling the empty column of 'Embarked' column with Mode of the same column
#Wll use Mode for Numerical columns
#Mode = value occured very often i.e. most frequent value

mode_embarked = df['Embarked'].mode()
mode_embarked

mode_embarked = df['Embarked'].mode()[0]
mode_embarked

df['Embarked'] = df['Embarked'].fillna(mode_embarked)

df.isnull().sum()

#Filling the 'Cabin' column
# Will fill 1 for cells with cabin value given, and 0 for empty

df['Has_Cabin'] = df['Cabin'].notna().astype(int)
#Creating a new column 'Has_cabin' with returned values as boolean. True if has value and False if not.
#astype() -> Converts boolean to int

df.drop('Cabin',axis = 1,inplace = True) #Deleteng the column 'Cabin' which is not required further more

df.isnull().sum()

df.head()

df['Has_Cabin'].value_counts()

"""DATA ANALYSIS - Analysing the data after cleaning to find the solution

Three types of Analysis:


*   Univariate Analysis - Analysing using Owo columns/factors
*   Bivariate Analysis - Analysing using Two columns/factors
*   Multivariate Analysis - Analysing using Two or more columns/factors
"""

##Setup up the figure for plotting
fig, axes = plt.subplots(2,3,figsize = (18,12))
fig.suptitle('Univerate analysis of Categorial features',fontsize = 16)

#plotting the each categorical column
sns.countplot(ax=axes[0,0],x = 'Survived', data = df).set_title('Survived')
sns.countplot(ax=axes[0,1],x = 'Pclass', data = df).set_title('Passenger class')
sns.countplot(ax=axes[0,2],x = 'Sex', data = df).set_title('Gender')
sns.countplot(ax=axes[1,0],x = 'Embarked', data = df).set_title('Embarked')
sns.countplot(ax=axes[1,1],x = 'SibSp', data = df).set_title('Sibling/spouse')
sns.countplot(ax=axes[1,2],x = 'Parch', data = df).set_title('Parents/children')

plt.tight_layout(rect =[0,0,1,0.96])
plt.show()

fig, axes = plt.subplots(1,2,figsize = (16,12))
fig.suptitle('Univerate analysis of Numerical features',fontsize = 16)

sns.histplot(ax = axes[0],data = df, x ='Age',kde = True, bins =30).set_title('Age Distribution')
sns.histplot(ax = axes[1],data = df, x ='Fare',kde = True, bins =40).set_title('Fare Distribution')

plt.show()

"""In Bivariate Analysis
*   For Categorial vs Numerical -> Barchart
*   For Categorical vs Categorical -> Stacked bars(crosstabs)
*   For Numerical vs Numerical -> Scatterplot






"""

fig, axes = plt.subplots(2,2,figsize = (16,12))
fig.suptitle('Bivariate analysis of Numerical features',fontsize = 16)

#Pclass vs Survived
sns.barplot(ax= axes[0,0], x = 'Pclass', y ='Survived', data = df).set_title('Pclass vs Survived')

#Sex vs Survived
sns.barplot(ax= axes[0,1], x = 'Sex', y ='Survived', data = df).set_title('Sex vs Survived')

#Embarked vs Survived
sns.barplot(ax= axes[1,0], x = 'Embarked', y ='Survived', data = df).set_title('Port vs Survived')

#Has_cabin vs Survived
sns.barplot(ax= axes[1,1], x = 'Has_Cabin', y ='Survived', data = df).set_title('Has_Cabin vs Survived')

plt.tight_layout(rect = [0,0,1,0.96])
plt.show()

#Age vs Survived

g =sns.FacetGrid(df, col= 'Survived', height = 6)
g.map(sns.histplot,'Age',bins = 25, kde = True)
plt.suptitle('Age distribution by Survival status', y = 1.02)
plt.show()

plt.figure(figsize=(10,8))
sns.boxplot(y = 'Fare',data=df)
plt.title('Box plot of Ticket Fare')
plt.ylabel('Fare')
plt.show()

"""FEATURE ENGINEERING"""

#1 create a 'FamilySize' feature
df['FamilySize'] = df['SibSp']+df['Parch']+1 #+1 is for person themselves

#2 creating a 'IsAlone' feature
df['IsAlone'] = 0
df.loc[df['FamilySize'] == 1,'IsAlone'] = 1

print("Created 'FamilySize' and 'IsAlone' features :")
df[['FamilySize','IsAlone']].head()

## Analyzing Family related features against Survival

fig, axes = plt.subplots(1,2,figsize = (16,6))

#FamilySize vs Survived
sns.barplot(ax= axes[0], x = 'FamilySize', y ='Survived', data = df).set_title('FamilySize vs Survived')

#IsAlone vs Survived
sns.barplot(ax= axes[1], x = 'IsAlone', y ='Survived', data = df).set_title('IsAlone vs Survived')
plt.show()

#3 Extract 'Title' from 'Name' Column
df['Title'] = df['Name'].str.extract(r'([A-Za-z]+)\.',expand = False)

df['Title'].unique()

df['Title'].value_counts()

#Simplify the titles by grouping rare ones into a 'Rare' Category
df['Title'] = df['Title'].replace(['Lady','Countess','Capt','Col','Don','Dr','Major','Rev','Sir','Jonkheer','Dona'],'Rare')

df['Title'] = df['Title'].replace('Mlle','Miss')
df['Title'] = df['Title'].replace('Ms','Miss')
df['Title'] = df['Title'].replace('Mme','Mrs')

plt.figure(figsize=(12,6))
sns.barplot(x = 'Title', y = 'Survived', data = df)
plt.title('Title vs Survival')
plt.ylabel('Survival Probability')
plt.show()

#Survival rate by Pclass and Sex

sns.catplot(x = 'Pclass', y = 'Survived', hue = 'Sex', data = df, kind = 'bar',height=6,aspect=1.5)
plt.title('Survival rate by Pclass and Sex')
plt.ylabel('Survival Probability')
plt.show()
#

#Violin plot tomsee age distribution by sex and survival states
plt.figure(figsize=(14,8))
sns.violinplot(x = 'Sex', y = 'Age', hue = 'Survived', data = df,split=True,palette={0: 'blue',1:'orange'})
plt.title('Age distribution by sex and survival')
plt.show()

"""CORRELATION ANALYSIS"""

#Correlation Heatmap for Numerical features
plt.figure(figsize = (14,10))
numeric_cols = df.select_dtypes(include=np.number)
correlation_matrix = numeric_cols.corr()
sns.heatmap(correlation_matrix,annot = True,cmap = 'coolwarm',fmt = '.2f')
plt.title('Correlation Heatmap for Numerical features')
plt.show()

"""YDATA PROFILING"""

# Generate profiling report
profile = ProfileReport(df, title="Titanic Data Profiling Report", explorative=True)

# Display
profile.to_notebook_iframe()

# save as HTML
profile.to_file("Titanic_Survival_Analysis_Report.html")