# -*- coding: utf-8 -*-
"""Titanic_Survival_Pr01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lSDPeaZ5M5d3ixeAVv7n0XTZoQnwibTk
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set(style = 'whitegrid')

!git clone 'https://github.com/Chinmaybharadwaj7/Sample-Dataset'

df = pd.read_csv('/content/Sample-Dataset/Titanic-Dataset.csv')

df.columns

df.head()

df.tail()

#values that the column holds
df['Embarked'].unique()

df.info()

df.describe()

#Describes the dataset(Only numerical Column)
#Calculates the basic statistics for dataset study

df['Cabin']

df['Cabin'].value_counts()

"""Step 3: Data Cleaning"""

#first we need to figure the cells which are not filled i.e. Empty
# True if Empty(Null)

df.isnull()

#total count of unknown value(null) in each column
df.isnull().sum()

#filling the empty column of 'Age' column with Median value of the same column
#Wll use Median for Numerical columns
#Median = Midlle Value of that column
median_age = df['Age'].median()
df['Age'] = df['Age'].fillna(median_age)

df.isnull().sum()

#filling the empty column of 'Embarked' column with Mode of the same column
#Wll use Mode for Numerical columns
#Mode = value occured very often i.e. most frequent value

mode_embarked = df['Embarked'].mode()
mode_embarked

mode_embarked = df['Embarked'].mode()[0]
mode_embarked

df['Embarked'] = df['Embarked'].fillna(mode_embarked)

df.isnull().sum()

"""Mode = most frequent value

Median = middle value

Mean = average value
"""

#Filling the 'Cabin' column
# Will fill 1 for cells with cabin value given, and 0 for empty

df['Has_Cabin'] = df['Cabin'].notna().astype(int)
#Creating a new column 'Has_cabin' with returned values as boolean. True if has value and False if not.
#astype() -> Converts boolean to int

df.drop('Cabin',axis = 1,inplace = True) #Deleteng the column 'Cabin' which is not required further more

df.isnull().sum()

df.head()

df['Has_Cabin'].value_counts()

"""Analysis"""

##Setup up the figure for plotting
fig, axes = plt.subplots(2,3,figsize = (18,12))
fig.suptitle('Univerate analysis of Categorial features',fontsize = 16)

#plotting the each categorical column
sns.countplot(ax=axes[0,0],x = 'Survived', data = df).set_title('Survived')
sns.countplot(ax=axes[0,1],x = 'Pclass', data = df).set_title('Passenger class')
sns.countplot(ax=axes[0,2],x = 'Sex', data = df).set_title('Gender')
sns.countplot(ax=axes[1,0],x = 'Embarked', data = df).set_title('Embarked')
sns.countplot(ax=axes[1,1],x = 'SibSp', data = df).set_title('Sibling/spouse')
sns.countplot(ax=axes[1,2],x = 'Parch', data = df).set_title('Parents/children')

plt.tight_layout(rect =[0,0,1,0.96])
plt.show()

fig, axes = plt.subplots(1,2,figsize = (16,12))
fig.suptitle('Univerate analysis of Numerical features',fontsize = 16)

sns.histplot(ax = axes[0],data = df, x ='Age',kde = True, bins =30).set_title('Age Distribution')
sns.histplot(ax = axes[1],data = df, x ='Fare',kde = True, bins =40).set_title('Fare Distribution')

plt.show()

fig, axes = plt.subplots(2,2,figsize = (16,12))
fig.suptitle('Bivariate analysis of Numerical features',fontsize = 16)

#Pclass vs Survived
sns.barplot(ax= axes[0,0], x = 'Pclass', y ='Survived', data = df).set_title('Pclass vs Survived')

#Sex vs Survived
sns.barplot(ax= axes[0,1], x = 'Sex', y ='Survived', data = df).set_title('Sex vs Survived')

#Embarked vs Survived
sns.barplot(ax= axes[1,0], x = 'Embarked', y ='Survived', data = df).set_title('Port vs Survived')

#Has_cabin vs Survived
sns.barplot(ax= axes[1,1], x = 'Has_Cabin', y ='Survived', data = df).set_title('Has_Cabin vs Survived')

plt.tight_layout(rect = [0,0,1,0.96])
plt.show()

